### ISSUE TITLE
Anjay-esp32-client 22.01 stop working with ANJAY_SECURITY_PSK

### ISSUE THREAD

**Issue by AxelLin** [AVSystem/Anjay-esp32-client#3]
I test Anjay-esp32-client 22.01 with server uri: coaps://leshan.eclipseprojects.io:5684,
then I got below errors:

E (3866) anjay: ERROR [avs_net] [/home/axel/Anjay-esp32-client/main/anjay/deps/avs_commons/src/net/mbedtls/avs_mbedtls_socket.c:913]: PSK support disabled
E (3876) anjay: ERROR [avs_net] [/home/axel/Anjay-esp32-client/main/anjay/deps/avs_commons/src/net/mbedtls/../avs_ssl_common.h:113]: socket initialization error
E (3896) anjay: ERROR [anjay] [/home/axel/Anjay-esp32-client/main/anjay/src/core/servers/anjay_connection_ip.c:87]: could not create CoAP socket

The issue is because removing define for AVS_COMMONS_NET_WITH_PSK
https://github.com/AVSystem/Anjay-esp32-client/commit/cf987a2a87b19af7a48100d0ad06fa74d23525fe#diff-d0d7ec43c37443919998aa1b9e30f94d2ccc8bb635e683f397abd13ff4c4b23bL555
BTW, Anjay-esp32-client 22.01 added define for AVS_COMMONS_WITH_AVS_CRYPTO_PSK but seems it's not used at all.

**Comment by Mierunski** [comment]
Sorry for the inconvenience, it seems that public and commercial configurations have gone out of sync accidentaly. Just pushed the fixed version
