### ISSUE TITLE
CMake error when running set-target command

### ISSUE THREAD

**Issue by AirWind001** [AVSystem/Anjay-esp32-client#6]
Hello,
I am using the ESP32 WROVER KIT. when i try to run the command idf.py set-target esp32. from the git folder directory it gives the error CMake Error at main/CMakeLists.txt:34 (add_library):
  No SOURCES given to target: anjay

the full verbose cmd line output is attached below
[error message.txt](https://github.com/AVSystem/Anjay-esp32-client/files/8160721/error.message.txt)

Any help would be much appreciated.

**Comment by Mierunski** [comment]
Hi!
It is possible that you have not initializes git submodules
try to run:
```
git submodule init
git submodule update --recursive
```
And then clean the build directories and run commands again

**Comment by AirWind001** [comment]
Thanks for the quick response!
Yes that was the issue and it is now fixed. Sorry, I'm new to git.

**Comment by Mierunski** [comment]
No problem, glad it worked!
